### ISSUE TITLE
Getting Exception after creating new VSPPackage

### ISSUE THREAD

**Issue by luis-cortina** [Microsoft/extendvs#54]
The exception is:
```
The "CreateZipPackage" task failed unexpectedly.System.TypeLoadException: 
Could not load type 'Microsoft.VisualStudio.Setup.PartialManifestType' 
from assembly 
'Microsoft.VisualStudio.Setup.Common, Version=1.0.0.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a'. 
at Microsoft.VisualStudio.Sdk.BuildTasks.CreateZipPackageBase.Execute()
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

Any idea where to look about this?

Luis

**Comment by sharwell** [comment]
I just started getting this today :(

**Comment by dazinator** [comment]
Just hit this too. Here is the `csproj` file: 

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\packages\Microsoft.VSSDK.BuildTools.15.1.192\build\Microsoft.VSSDK.BuildTools.props" Condition="Exists('..\packages\Microsoft.VSSDK.BuildTools.15.1.192\build\Microsoft.VSSDK.BuildTools.props')" />
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectTypeGuids>{82b43b9b-a64c-4715-b499-d71e9ca2bd60};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <ProjectGuid>{E2D0A2E6-47DA-4DB9-BEFD-EF9C04E2E980}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>CslaTemplates</RootNamespace>
    <AssemblyName>CslaTemplates</AssemblyName>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
    <GeneratePkgDefFile>false</GeneratePkgDefFile>
    <IncludeAssemblyInVSIXContainer>false</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>false</IncludeDebugSymbolsInVSIXContainer>
    <IncludeDebugSymbolsInLocalVSIXDeployment>false</IncludeDebugSymbolsInLocalVSIXDeployment>
    <CopyBuildOutputToOutputDirectory>false</CopyBuildOutputToOutputDirectory>
    <CopyOutputSymbolsToOutputDirectory>false</CopyOutputSymbolsToOutputDirectory>
    <MinimumVisualStudioVersion>15.0</MinimumVisualStudioVersion>
    <FileUpgradeFlags>
    </FileUpgradeFlags>
    <UpgradeBackupLocation>
    </UpgradeBackupLocation>
    <OldToolsVersion>14.0</OldToolsVersion>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>CslaKey.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>csla.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\..\license.md">
      <Link>license.rtf</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="..\..\..\readme.md">
      <Link>readme.rtf</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <None Include="CslaKey.snk" />
    <Content Include="ItemTemplates\CSharp\Csla4\AuthorizationRule.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\BusinessRule.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\CommandObject.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\DynamicRoot.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\DynamicRootList.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\EditableChild.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\EditableChildList.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\EditableRoot.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\EditableRootParent.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\NameValueList.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\ObjectFactory.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\ReadOnlyChild.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\ReadOnlyChildList.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\ReadOnlyList.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\ReadOnlyRoot.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\SwitchableObject.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\AuthorizationRule.zip" />
    <Content Include="ItemTemplates\VisualBasic\Csla4\BusinessRule.zip" />
    <Content Include="ItemTemplates\CSharp\Csla4\DynamicRootBindingList.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\EditableChildBindingList.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\EditableRootBindingList.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\EditableRootList.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\ReadOnlyBindingList.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\CSharp\Csla4\ReadOnlyChildBindingList.zip">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\CommandObject.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\DynamicRoot.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\DynamicRootBindingList.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\DynamicRootList.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\EditableChild.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\EditableChildBindingList.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\EditableChildList.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\EditableRoot.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\EditableRootBindingList.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\EditableRootList.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\EditableRootParent.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\NameValueList.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\ReadOnlyBindingList.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\ReadOnlyChild.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\ReadOnlyChildBindingList.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\ReadOnlyChildList.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\ReadOnlyList.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\ReadOnlyRoot.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ItemTemplates\VisualBasic\Csla4\SwitchableObject.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <None Include="packages.config" />
    <None Include="source.extension.vsixmanifest">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="csla.ico" />
  </ItemGroup>

  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Microsoft.VSSDK.BuildTools.15.1.192\tools\vssdk\Microsoft.VsSDK.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.VSSDK.BuildTools.15.1.192\tools\vssdk\Microsoft.VsSDK.targets'))" />
    <Error Condition="!Exists('..\packages\Microsoft.VSSDK.BuildTools.15.1.192\build\Microsoft.VSSDK.BuildTools.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.VSSDK.BuildTools.15.1.192\build\Microsoft.VSSDK.BuildTools.props'))" />
    <Error Condition="!Exists('..\packages\Microsoft.VSSDK.BuildTools.15.1.192\build\Microsoft.VSSDK.BuildTools.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.VSSDK.BuildTools.15.1.192\build\Microsoft.VSSDK.BuildTools.targets'))" />
  </Target>
  <Import Project="..\packages\Microsoft.VSSDK.BuildTools.15.1.192\tools\vssdk\Microsoft.VsSDK.targets" Condition="Exists('..\packages\Microsoft.VSSDK.BuildTools.15.1.192\tools\vssdk\Microsoft.VsSDK.targets')" />
  <Import Project="..\packages\Microsoft.VSSDK.BuildTools.15.1.192\build\Microsoft.VSSDK.BuildTools.targets" Condition="Exists('..\packages\Microsoft.VSSDK.BuildTools.15.1.192\build\Microsoft.VSSDK.BuildTools.targets')" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>
```

**Comment by zeaposs** [comment]
Got this myself today. Pretty much it's because the old (15.0.26201) and new (15.1.192) VSSDK Buildtools don't like each other too much. I've killed the MSBuild process and after that the problem was gone.
